apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rollout.yaml
  - service.yaml
  - backend-config.yaml
  - ingress.yaml
  - tls.yaml

commonLabels:
  app: demo-web-canary
