apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-web-canary
spec:
  replicas: 1
  revisionHistoryLimit: 0
  template:
    spec:
      containers:
        - name: demo-web-canary
          image: demo-web-canary
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: demo-web-canary-configmap
          ports:
            - containerPort: 8888
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
  strategy:
    canary:
      canaryService: demo-web-canary
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}       
    
