apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: demo-web-external-secret
  namespace: demo-web-dev
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-backend          
  target:                                                             
    name: demo-web-secret
  data:                                                       
  - secretKey: demo-web-secret
    remoteRef:            
      key: demo-web-secret  
      version: "2"