apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-web-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    kubernetes.io/ingress.class: nginx-private
spec:
  rules:
    - host: demo-web-dev.squantumengine.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-web-service
                port:
                  number: 8888
  tls:
  - hosts: 
    - demo-web-dev.squantumengine.com
    secretName: demo-web-tls-secret