apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/backend-config: '{"default": "demo-web-config"}'
  name: demo-web-service
spec:
  ports:
    - port: 8888
      protocol: TCP
      targetPort: 8888
