apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/demo-web

configMapGenerator:
- envs:
  - app.env
  name: demo-web-configmap
  
commonLabels:
  app: demo-web
  database: disabled
  tier: frontend

images:
- name: demo-web
  newName: asia-southeast2-docker.pkg.dev/sqe-non-prod/devops/dev/demo-web
  newTag: 78faae49f93a95f33ca72804558f164fb781e72f

patches:
- path: ingress-patch.yaml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: vdemo-web-ingress
    version: v1
- path: tls-patch.yaml
  target:
    group: cert-manager.io
    kind: Certificate
    name: demo-web-tls
    version: v1

namespace: demo-web-stg
