apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: gcp-backend
spec:
  provider:
      gcpsm:                                                                            
        projectID: sqe-non-prod
        workloadIdentity:
          # name of the cluster region
          clusterLocation: asia-southeast2
          # name of the GKE cluster
          clusterName: sqe-non-production-gke-cluster	
          # reference the sa from above
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets