apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: gcp-backend
spec:
  provider:
      gcpsm:                                                  
        auth:
          secretRef:
            secretAccessKeySecretRef:
              name: demo-web-secret                        
              key: demo-web-secret
              namespace: external-secrets                             
        projectID: sqe-non-prod