apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: gcp-backend
spec:
  provider:
      gcpsm:                                                  
        # auth:
        #   secretRef:
        #     secretAccessKeySecretRef:
        #       name: gcpsm-secret                       
        #       key: secret-access-credentials
        #       namespace: default                            
        projectID: sqe-non-prod