apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/demo-web-canary

configMapGenerator:
- envs:
  - app.env
  name: demo-web-canary-configmap
  
commonLabels:
  app: demo-web-canary


images:
- name: demo-web-canary
  newName: asia-southeast2-docker.pkg.dev/sqe-non-prod/devops/dev/demo-web
  newTag: 0265316579f417ecc882ecd2b7d9953fab3ac9f5
- name: demo-web-canary-dev
  newName: asia-southeast2-docker.pkg.dev/sqe-non-prod/devops/dev/demo-web
  newTag: a1b4c01d9cfb30160b7b65c8c18c68583b334b71

namespace: demo-web-canary-dev
