apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/demo-web-canary

configMapGenerator:
- envs:
  - app.env
  name: demo-web-canary-configmap
  
commonLabels:
  app: demo-web-canary


images:
- name: demo-web-canary
  newName: asia-southeast2-docker.pkg.dev/sqe-non-prod/devops/dev/demo-web
  newTag: 9dc514ca5cfacebdf8d54d47468d97cecb1ea6cc

namespace: demo-web-canary-dev
