apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/demo-web

configMapGenerator:
- envs:
  - app.env
  name: demo-web-configmap
  
commonLabels:
  app: demo-web


images:
- name: demo-web
  newName: asia-southeast2-docker.pkg.dev/sqe-non-prod/devops/dev/demo-web
  newTag: 866d9cc41fab6aa775612285f7c3c1986ed5e3e4

namespace: demo-web-dev
