apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/demo-web

configMapGenerator:
- envs:
  - app.env
  name: demo-web-configmap
  
commonLabels:
  app: demo-web


images:
- name: demo-web
  newName: asia-southeast2-docker.pkg.dev/sqe-non-prod/devops/dev/demo-web
  newTag: ea68dafd68230102650a3fe1f5bac19975132fb0

namespace: demo-web-dev
