apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/demo-web

configMapGenerator:
- envs:
  - app.env
  name: demo-web-configmap
  
commonLabels:
  app: demo-web


images:
- name: demo-web
  newName: asia-southeast2-docker.pkg.dev/sqe-non-prod/devops/dev/demo-web
  newTag: a1b4c01d9cfb30160b7b65c8c18c68583b334b71

namespace: demo-web-dev
